### ISSUE TITLE
Property-based form parameters for application/x-www-form-urlencoded header style

### ISSUE THREAD

**Issue by rigolepe** [atomicbits/scraml#128]
See: https://github.com/raml-org/raml-spec/issues/613

```
/helloWorld:
  post:
    body:
      application/x-www-form-urlencoded:
        properties:
          name:
            description: name on account
            type: string
            example: Naruto Uzumaki
          gender:
            enum: ["male", "female"]
```
