### ISSUE TITLE
A simple string body type generates multiple actions with te same body type (string) in the DSL 

### ISSUE THREAD

**Issue by rigolepe** [atomicbits/scraml#129]
E.g. 

```
  post:
    body:
      plain/text:
        type: string
        required: false
```
