### ISSUE TITLE
Escaping fields that overlap with Scala keywords using backticks

### ISSUE THREAD

**Issue by rigolepe** [atomicbits/scraml#153]
Fields that overlap with Scala keywords are now escaped by adding a $ at the end of the field name. In Scala, we better use backticks: 

```
Layer:
    type: object
    discriminator: type
    properties:
      type: string
      id: string
      titel: string
```

```
case class Layer(`type`: String, ...) 
```
