### ISSUE TITLE
Subclass with no extra properties is not generated

### ISSUE THREAD

**Issue by rigolepe** [atomicbits/scraml#154]
```
Layer:
  type: object
  properties:
    name: string
```

```
SpecialLayer:
  type: Layer
  properties:
```

The SpecialLayer isn't generated in the Scala client.
