### ISSUE TITLE
Add optional configuration for a default outgoing charset

### ISSUE THREAD

**Issue by rigolepe** [atomicbits/scraml#67]
Outgoing requests with string bodies get their charset from the 'charset' field in the Content-Type header:

```yaml
  put:
    is: [acceptjson, error401, error404]
    description: Update a foo object.
    body:
      application/json;charset=utf-8:
```

If the 'charset=utf-8' part is omitted in the request body mimetype, then the underlying client (currently mostly ning) chooses a default charset (assumably ascii). This feature will allow the user to set a default outgoing charset that is added to the outgoing Content-Type if it is not yet present. 

Update: de default will be the Java environment default charset if no charset is present.
